//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
            this.AnswerVotes = new HashSet<AnswerVote>();
        }
    
        public int AnsId { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int PostId { get; set; }
        public int Score { get; set; }
        public int AnsUserId { get; set; }
    
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<AnswerVote> AnswerVotes { get; set; }
    }
}
