//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public int JobPostCount { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public string CDescription { get; set; }
        public string CCategory { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
