//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public int JPId { get; set; }
        public System.DateTime JPCreationDate { get; set; }
        public Nullable<System.DateTime> JPDeleteDate { get; set; }
        public int Views { get; set; }
        public string Body { get; set; }
        public int JobId { get; set; }
        public string Title { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
